### PR TITLE
Add atbash-cipher

### PR DESCRIPTION
**Pull request by kytrinyx**
This is a cherry-pick of @ebengt's work in #29 -- I updated the module import statement to not have spaces so that it would work with the (old) test runner. I was on a flight and didn't see the updated test runner until just now.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Look good, should squash the commits to make the history pretty.

**Comment by kytrinyx** [comment]
Cool, I'll do that.

**Comment by kytrinyx** [comment]
Done

**Comment by tmcgilchrist** [comment]
nice :boom:

**Pull request merged**
