### PR TITLE
Reindent all the exercises

### PR DESCRIPTION
**Pull request by kytrinyx**
There was some inconsistent spacing across the board. I have no idea if this is something we want, but I went ahead and ran all the files through my syntax/indentation settings.

### CODE REVIEW

**Comment by tmcgilchrist** [comment]
Personally I'm not too fazed as long as there's no tabs, they're just evil. :-)

**Comment by kytrinyx** [comment]
Ah, I think my current syntax file is all tabs. Let me fix that. What is the usual choice for erlang for indentation? 2 spaces? 4 spaces?

**Comment by tmcgilchrist** [comment]
4 spaces is more common in my experience, Erlang/OTP uses 4 and so does Basho.

**Comment by kytrinyx** [comment]
Cool, I'll do that then. Thanks :) I'm having fun playing with erlang, even though I'm not actually doing any real programming in it.

**Comment by tmcgilchrist** [comment]
This'll need to be redone / rebased / re-something before merging. Think I'd be a good idea to keep the formatting somewhat consistent.

**Comment by macintux** [comment]
Sorry, didn't notice this pull request before making several changes. If nothing else I'd have at least fixed indentation to 4 spaces before submitting my PRs.

**Comment by kytrinyx** [comment]
Oh, hah. I completely forgot about this PR. I'll redo it :)

**Comment by kytrinyx** [comment]
It looks like the files had all been reformatted. Closing :)

**Pull request closed without merging**
