### PR TITLE
add track icon into img folder

### PR DESCRIPTION
**Pull request by PurityControl**
Pull request to resolve issue #101

### CODE REVIEW

**Comment by NobbZ** [comment]
Thank you!
But as far as I understand the explanation in #101 and exercism/exercism.io#2925, the icon needs to be named `icon.{png,svg}`, also 693x693 pixels seems quite large to me, and I like to keep that resolution only if it is really necessary.

@kytrinyx: Will a nearly full screen image (it is fullscreen on my phone!) be really necessary on any page, or is a downscale to a more common icon resolution possible? I'm thinking about 128x128 pixels at most, always having my mobile data plan in mind.

**Comment by PurityControl** [comment]
Sorry, more haste less speed. The file is named correctly now. Let me know when you settle on a resolution and I can make the necessary changes.

**Comment by kytrinyx** [comment]
I don't think we'll ever need a huge image. I think 300x300 should be more than enough. It would be great to get SVGs for our data plans!

**Comment by PurityControl** [comment]
I have changed the png resolution to 300x300 and added an additional icon file in svg format.

**Comment by NobbZ** [comment]
Sorry @PurityControl, some reallife happened, hope beeing back again…

Thank you!

**Pull request merged**
