### PR TITLE
add hello-world exercise

### PR DESCRIPTION
**Pull request by barberj**
Trivial, but no harm in having.

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice! I can't speak to the test suite and reference solution since I'm not a track maintainer on Erlang, but we've actually been talking about adding hello world exercises to all the tracks. This addresses https://github.com/exercism/todo/issues/30

Would you mind squashing the commits?

**Comment by barberj** [comment]
as you wish :)

**Comment by kytrinyx** [comment]
`:D`

**Comment by tmcgilchrist** [comment]
Looks fine to me. :rocket:

**Pull request merged**
