### PR TITLE
Added triangle

### PR DESCRIPTION
**Pull request by NobbZ**

### CODE REVIEW

**Comment by NobbZ** [comment]
OK, I forgot to put it into configuration. Will do that tomorrow, PC is already shut down.

**Comment by tmcgilchrist** [comment]
Looks good, once it's in the config I'll merge this.

**Comment by NobbZ** [comment]
OK, have committed

**Comment by NobbZ** [comment]
I inserted triangle to the end, perhaps we might find a position that is more suitable, since it is a very easy exercise and doable straight away.

**Pull request merged**
