### PR TITLE
Normalize format of config file

### PR DESCRIPTION
**Pull request by kytrinyx**
This will let us script changes to it with less noise in the diffs.

### CODE REVIEW

**Comment by NobbZ** [comment]
Is the normalizer available somewhere, such that we can integrate it into CI?

**Comment by kytrinyx** [comment]
I wrote an ad-hoc script using the Ruby json library, but I could probably add this as a feature to configlet. Let me investigate.

**Comment by NobbZ** [comment]
@kytrinyx can you rebase?

**Comment by kytrinyx** [comment]
When I rebased against master there were no further changes. Closed.

**Pull request closed without merging**
