### PR TITLE
Fix vsn attributes

### PR DESCRIPTION
**Pull request by xymbol**
Save users from seeing a warning message on every run.

```
===> Verifying dependencies...
===> Compiling hello_world
===> Getting log of git dependency failed in /Users/adrian/exercism/erlang/hello-world. Falling back to version 0.0.0
===> Performing EUnit tests...
======================== EUnit ========================
file "hello_world.app"
  application 'hello_world'
    module 'hello_world'
      module 'hello_world_tests'
        hello_world_tests: version_test...ok
        hello_world_tests: say_hi_test...ok
        [done in 0.006 s]
      [done in 0.006 s]
    [done in 0.006 s]
  [done in 0.007 s]
=======================================================
  2 tests passed.
```

Setting `vsn` to a known value makes `rebar` happy.

### CODE REVIEW

**Comment by NobbZ** [comment]
Thanks for doing this! I did not realize any warnings locally though.

**Comment by xymbol** [comment]
@NobbZ They don't show up if running from a working copy.

**Comment by NobbZ** [comment]
Ah, OK, this explains a lot. Nearly everything I deal with is `git`ted in one way or the other...

**Comment by xymbol** [comment]
Sure, the Exercism client does not create a repo on fetch.

**Pull request merged**
